[package]
name = "netcache_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
bytes = "1.6"
log = "0.4"
env_logger = "0.11"
lazy_static = "1.4"
zstd = "0.13"
zstd-safe = "6.0"
