# config.toml

[socket]
mode = "tcp"               # "unix" oder "tcp"
path = "/tmp/netcache.sock" # Pfad zur socket Datei
addr = "127.0.0.1:8787"     # Nur relevant bei TCP

[storage]
max_ram_size = 104857600    # maximale ram größe in Bytes
ttl_checktime = 5          # Wartezeit zwischen den ttl checks

[sync]
enabled = true
server_addr = "tcp://192.168.1.10:9000" # Eigene Adresse
peers = [
  "tcp://192.168.1.10:9000",
  "tcp://192.168.1.11:9000",
  "tcp://192.168.1.12:9000"
]
sync_interval = 10 # Sekunden

[eventrelay]
mode = "tcp"                # "tcp" oder "unix"
addr = "127.0.0.1:9797"      # TCP-Adresse für EventRelay
path = "/tmp/eventrelay.sock" # Pfad für Unix-Socket (nur bei mode = "unix")