# config.toml

[socket]
mode = "tcp"               # "unix" oder "tcp"
path = "/tmp/netcache.sock" # Pfad zur socket Datei
addr = "127.0.0.1:8789"     # Nur relevant bei TCP

[storage]
max_ram_size = 104857600    # maximale ram größe in Bytes
ttl_checktime = 5          # Wartezeit zwischen den ttl checks

[sync]
enabled = true
server_addr = "192.168.178.35:9002" # Eigene Adresse
peers = [
  "192.168.178.35:9000",
  "192.168.178.35:9001",
  "192.168.178.35:9002",
]
sync_interval = 10 # Sekunden

[eventrelay]
mode = "tcp"                # "tcp" oder "unix"
addr = "127.0.0.1:9799"      # TCP-Adresse für EventRelay
path = "/tmp/eventrelay.sock" # Pfad für Unix-Socket (nur bei mode = "unix")